# Generated by Django 3.0.5 on 2020-09-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0002_auto_20200903_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Upload_Img',
            field=models.ImageField(help_text='100 characters max.', upload_to='images/'),
        ),
    ]
