# Generated by Django 3.0.5 on 2020-09-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0003_auto_20200904_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Upload_Img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
